Document: glktermw
Title: Debian glktermw Manual
Author: <insert document author here>
Abstract: This manual describes what glktermw is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glktermw/glktermw.sgml.gz

Format: postscript
Files: /usr/share/doc/glktermw/glktermw.ps.gz

Format: text
Files: /usr/share/doc/glktermw/glktermw.text.gz

Format: HTML
Index: /usr/share/doc/glktermw/html/index.html
Files: /usr/share/doc/glktermw/html/*.html
